Feature/apps 2064
Alfresco/googledrive pull request #589
Opened 2023-08-29 03:59 UTC by MohinishSah

2023-08-29 03:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Alfresco/googledrive?pullRequest=589) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Alfresco/googledrive?pullRequest=589) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: MohinishSah<br/>:white_check_mark: omkaryadv177<br/>:x: Mohinish Sah<br/><hr/>**Mohinish Sah** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Alfresco/googledrive?pullRequest=589) it.</sub>

2023-09-01 11:42 UTC, kavitshah-gl requested changes

2023-09-01 11:42 UTC, kavitshah-gl commented on .github/workflows/build.yml
> +      - 'feature/**'
Do we require this one?

2023-09-01 11:42 UTC, kavitshah-gl commented on .github/workflows/build.yml
> +    if: ${{ ( startsWith(github.ref_name, 'HF/')  || startsWith(github.ref_name, 'SP/') || github.ref_name == 'master' ) &&
you can revert this change.

2023-09-01 11:42 UTC, kavitshah-gl commented on alfresco-googledrive-end-to-end-tests/pom.xml
> +                                    <name>alfresco/alfresco-activemq:5.17.4-jre17-rockylinux8</name>
Why are we downgrading the version?

2023-09-04 06:49 UTC, kavitshah-gl approved these changes
Approved

2023-09-04 07:12 UTC, MohinishSah commented on alfresco-googledrive-end-to-end-tests/pom.xml
> +                                    <name>alfresco/alfresco-activemq:5.17.4-jre17-rockylinux8</name>
rebased the branch again and fixed

2023-09-04 07:12 UTC, merged